#!/usr/bin/python
import sys, socket, subprocess

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('localhost', 5050))
while True:
	command = sock.recvfrom(4096)
	print(command)
	if not command:
		continue
	try:
		subprocess.call(command[0].split())
	except OSError:
		print('That cannot be done')
